### PR TITLE
feat: custom drag-n-drop

### PR DESCRIPTION
**Pull request by doinkythederp**
## Describe the changes this PR makes. Why should it be merged?

Updates drag-n-drop to show the actual node that will be placed before the user places it.

https://github.com/user-attachments/assets/841e851a-a40a-4ccd-b5fa-72276d052754

### CODE REVIEW

**Comment by doinkythederp** [comment]
Clicking on "ADI expander" currently crashes the entire app on this branch

**Comment by Tropix126** [comment]
I think there should be higher opacity while dragging over the sidebar.

**Comment by doinkythederp** [comment]
> Some minor UI nits:
> 
> * I think there should be higher opacity or no opacity at all while dragging over the sidebar, just for the purpose of readability.
> * Maybe adding a box-shadow while the node is being dragged would also be good, so that the user can distinguish  a dragged node from a node already on the graph.
> * The device node is being rendered outside of a svelte-flow `<Node />` meaning the interactive-primary border is missing. See the style for `.svelte-flow__node` in `flow.css` for styling that.


https://github.com/user-attachments/assets/8c3f7a9a-a41a-4771-af64-a19a030e4476

**Comment by Tropix126** [comment]
LGTM

**Pull request merged**
